### ISSUE TITLE
Tag team with intravert ?

### ISSUE THREAD

**Issue by edwardcapriolo** [mkjellman/perlcassa#17]
Hey, I notice the approach you are taking with your API is very close to some of the aspects https://github.com/zznate/intravert-ug is offering. Essentially working with simple objects like lists, hashes, etc. Doing type encoding etc. Just wanted to say good work, and that maybe what we are doing fits together very well.

**Comment by mkjellman** [comment]
More than happy to work together. Just wondering in what ways you would like to combine the Java code with our Perl code. Make it it optionally use intravert instead of thrift?

**Comment by edwardcapriolo** [comment]
Well I see you guys have done a good deal of word to help thrift get data from CQL columns. I am not really sure what the projects position is on READ/ONLY READ/WRITE CQL3 sparse tables from thrift. Also not sure exactly if anyone is going to make a binary transport for perl or if this is going to be left up to the "community". 

IntraVert going to provide an easy to work with JSON over http interface, and it is still early going but I am dedicated to making it possible to READ and WRITE data to CQL3s sparse tables from an RPC style interface. We (the RPC people) do not want to get locked out of the sparse table party.

**Comment by Lanzaa** [comment]
@edwardcapriolo Thanks for the information.

I think creating a REST/RPC http protocol for use with Cassandra is a great idea. However, I'm not sure how the perlcassa project can help with the intravert-ug project. I hope the project goes well.

As for the binary protocol, I believe the current plan is to stick with thrift in perlcassa until there is a compelling reason to swtich. There is at least one project I know of working on the binary protocol for perl and another working on an easy to wrap library in C++. The thrift interface to Cassandra should not be going away for a while.

I wish the intravert-ug project the best, but I'm not sure how perlcassa can contribute. Please reopen this issue and explain if you think otherwise.
